=== UO306603/SEW/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.uniovi.es"
           xmlns="http://www.uniovi.es"
           elementFormDefault="qualified">

	<!-- Restricciones-->
	<xs:simpleType name="tipoRangoLatitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90.0" />
			<xs:maxInclusive value="90.0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoRangoLongitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180.0" />
			<xs:maxInclusive value="180.0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoCategoriaPuerto">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Especial" />
			<xs:enumeration value="1ª" />
			<xs:enumeration value="2ª" />
			<xs:enumeration value="3ª" />
			<xs:enumeration value="4ª" />
		</xs:restriction>
	</xs:simpleType>

	
	<!-- Elementos con atributos -->
	<xs:element name="longitud_etapa">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="velocidad_media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia_salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="latitud_geo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoRangoLatitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud_geo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoRangoLongitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	
	<!-- Estructura Principal -->
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud_geo" />
				<xs:element ref="latitud_geo" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ciudad" type="xs:string" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ciudad" type="xs:string" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puerto_montana">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre_hito" type="xs:string" />
				<xs:element name="categoria" type="tipoCategoriaPuerto" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia_salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sprint">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre_hito" type="xs:string" />
				<xs:element name="tipo_sprint" type="xs:string" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia_salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="numero" type="xs:positiveInteger" />
				<xs:element ref="longitud_etapa" />
				<xs:element name="fecha" type="xs:date" />
				<xs:element name="tiempo_ganador" type="xs:duration" />
				<xs:element ref="velocidad_media" />
				<xs:element ref="desnivel" />
				<xs:element ref="inicio" />
				<xs:element ref="meta" />
				<xs:element name="tipo" type="xs:string" />

				<xs:element name="referencias">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="referencia" type="xs:anyURI" minOccurs="3" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="galeria_fotografias">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fotografia" type="xs:string" minOccurs="1" maxOccurs="5" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="galeria_videos" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="video" type="xs:string" minOccurs="1" maxOccurs="3" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="galeria_audios" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="audio" type="xs:string" minOccurs="1" maxOccurs="3" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="hitos">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="puerto_montana" />
							<xs:element ref="sprint" />
						</xs:choice>
					</xs:complexType>
				</xs:element>

				<xs:element name="puntos_anonimos">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="punto_anonimo" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nombre_punto" type="xs:string" minOccurs="0" />
										<xs:element ref="coordenadas" />
										<xs:element ref="distancia_salida" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="clasificacion_etapa" type="tipoClasificacion" />
				<xs:element name="clasificacion_general" type="tipoClasificacion" />
				<xs:element name="clasificacion_equipos" type="tipoClasificacionEquipos" />

			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<!-- Tipos Complejos -->
	<xs:complexType name="tipoClasificacion">
		<xs:sequence>
			<xs:element name="primero">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_participante" type="xs:string" />
						<xs:element name="tiempo" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="segundo">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_participante" type="xs:string" />
						<xs:element name="diferencia" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="tercero">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_participante" type="xs:string" />
						<xs:element name="diferencia" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoClasificacionEquipos">
		<xs:sequence>
			<xs:element name="equipo_primero">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_equipo" type="xs:string" />
						<xs:element name="tiempo" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipo_segundo">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_equipo" type="xs:string" />
						<xs:element name="diferencia" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipo_tercero">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nombre_equipo" type="xs:string" />
						<xs:element name="diferencia" type="xs:duration" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== UO306603/SEW/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombre>Andorra la Vella a Andorra la Vella</nombre>
    <numero>4</numero>
    <longitud_etapa unidad="km">104.8</longitud_etapa>
    <fecha>2026-08-25</fecha>
    <tiempo_ganador>PT2H40M35S</tiempo_ganador>
    <velocidad_media unidad="km/h">39.157</velocidad_media>
    <desnivel unidad="m">2953</desnivel>
    
    <inicio>
        <ciudad>Andorra la Vella</ciudad>
        <coordenadas>
            <longitud_geo unidad="grados decimales">1.5211</longitud_geo>
            <latitud_geo unidad="grados decimales">42.5078</latitud_geo>
            <altitud unidad="m">1023 </altitud>
        </coordenadas>
    </inicio>
    
    <meta>
        <ciudad>Andorra la Vella</ciudad>
         <coordenadas>
            <longitud_geo unidad="grados decimales">1.5211</longitud_geo>
            <latitud_geo unidad="grados decimales">42.5078</latitud_geo>
            <altitud unidad="m">1023 </altitud>
        </coordenadas>
    </meta>
    
    <tipo>montaña</tipo>
    
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-4</referencia>
        <referencia>https://www.lavuelta.es/es/clasificaciones/etapa-4</referencia>
        <referencia>https://www.lavuelta.es/es/video/3610/minuto-maillot-rojo-carrefour-etapa-4-la-vuelta-26</referencia>
    </referencias>
    
    <galeria_fotografias>
        <fotografia>foto1</fotografia>
        <fotografia>foto2</fotografia>
        <fotografia>foto3</fotografia>
    </galeria_fotografias>
    
    <galeria_videos>
        <video>video1</video>
        <video>video2</video>
    </galeria_videos>
    
    <galeria_audios>
        <audio>audio1</audio>
        <audio>audio2</audio>
    </galeria_audios>
    
    <hitos>
        <!-- Puerto 1: Port d'Envalira -->
    <puerto_montana>
        <nombre_hito>Port d'Envalira</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.71989</longitud_geo>
            <latitud_geo unidad="grados">42.54037</latitud_geo>
            <altitud unidad="m">2409 </altitud>
        </coordenadas>
        <distancia_salida unidad="km">25.1</distancia_salida>
    </puerto_montana>

    <!-- Puerto 2: Collada de Beixalis -->
    <puerto_montana>
        <nombre_hito>Collada de Beixalis</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.54771</longitud_geo>
            <latitud_geo unidad="grados">42.52908</latitud_geo>
            <altitud unidad="m">1795</altitud>
        </coordenadas>
        <distancia_salida unidad="km">59.3</distancia_salida>
    </puerto_montana>

    <!-- Sprint 1: Ordino -->
    <sprint>
        <nombre_hito>Ordino</nombre_hito>
        <tipo_sprint>Intermedio</tipo_sprint>
        <coordenadas>
            <longitud_geo unidad="grados">1.53319</longitud_geo>
            <latitud_geo unidad="grados">42.55623</latitud_geo>
            <altitud unidad="m">1298</altitud>
        </coordenadas>
        <distancia_salida unidad="km">68.4</distancia_salida>
    </sprint>

    <!-- Puerto 3: Col de Ordino -->
    <puerto_montana>
        <nombre_hito>Col de Ordino</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.5722</longitud_geo>
            <latitud_geo unidad="grados">42.5561</latitud_geo>
            <altitud unidad="m">1980</altitud>
        </coordenadas>
        <distancia_salida unidad="km">78.7</distancia_salida>
    </puerto_montana>

    <!-- Puerto 4: Alto de La Comella -->
    <puerto_montana>
        <nombre_hito>Alto de La Comella</nombre_hito>
        <categoria>3ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.531415</longitud_geo>
            <latitud_geo unidad="grados">42.500534</latitud_geo>
            <altitud unidad="m">1347</altitud>
        </coordenadas>
        <distancia_salida unidad="km">100.0</distancia_salida>
    </puerto_montana>
    </hitos>
    
    <puntos_anonimos>
    <punto_anonimo>
        <nombre_punto>Encamp</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5822</longitud_geo>
            <latitud_geo unidad="grados">42.5361</latitud_geo>
            <altitud unidad="m">1300</altitud>
        </coordenadas>
        <distancia_salida unidad="km">1.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Comienza puerto</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5830</longitud_geo>
            <latitud_geo unidad="grados">42.5370</latitud_geo>
            <altitud unidad="m">1310</altitud>
        </coordenadas>
        <distancia_salida unidad="km">1.8</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Canillo</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5977</longitud_geo>
            <latitud_geo unidad="grados">42.5667</latitud_geo>
            <altitud unidad="m">1530</altitud>
        </coordenadas>
        <distancia_salida unidad="km">8.1</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>El Tarter</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6531</longitud_geo>
            <latitud_geo unidad="grados">42.5794</latitud_geo>
            <altitud unidad="m">1710</altitud>
        </coordenadas>
        <distancia_salida unidad="km">13.2</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Soldeu</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6678</longitud_geo>
            <latitud_geo unidad="grados">42.5767</latitud_geo>
            <altitud unidad="m">1825</altitud>
        </coordenadas>
        <distancia_salida unidad="km">15.8</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Pas de la Casa</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7336</longitud_geo>
            <latitud_geo unidad="grados">42.5428</latitud_geo>
            <altitud unidad="m">2080</altitud>
        </coordenadas>
        <distancia_salida unidad="km">29.9</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Francia</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7380</longitud_geo>
            <latitud_geo unidad="grados">42.5440</latitud_geo>
            <altitud unidad="m">2085</altitud>
        </coordenadas>
        <distancia_salida unidad="km">30.3</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Andorra</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7350</longitud_geo>
            <latitud_geo unidad="grados">42.5430</latitud_geo>
            <altitud unidad="m">2070</altitud>
        </coordenadas>
        <distancia_salida unidad="km">31.1</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Tunel 2.870 metros iluminado</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7198</longitud_geo>
            <latitud_geo unidad="grados">42.5453</latitud_geo>
            <altitud unidad="m">2000</altitud>
        </coordenadas>
        <distancia_salida unidad="km">31.4</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>pasos estrechos por casetas de peaje</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6912</longitud_geo>
            <latitud_geo unidad="grados">42.5580</latitud_geo>
            <altitud unidad="m">1950</altitud>
        </coordenadas>
        <distancia_salida unidad="km">34.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Soldeu</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6678</longitud_geo>
            <latitud_geo unidad="grados">42.5767</latitud_geo>
            <altitud unidad="m">1825</altitud>
        </coordenadas>
        <distancia_salida unidad="km">38.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>El Tarter</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6531</longitud_geo>
            <latitud_geo unidad="grados">42.5794</latitud_geo>
            <altitud unidad="m">1710</altitud>
        </coordenadas>
        <distancia_salida unidad="km">41.0</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Canillo</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5977</longitud_geo>
            <latitud_geo unidad="grados">42.5667</latitud_geo>
            <altitud unidad="m">1530</altitud>
        </coordenadas>
        <distancia_salida unidad="km">46.0</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Encamp</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5822</longitud_geo>
            <latitud_geo unidad="grados">42.5361</latitud_geo>
            <altitud unidad="m">1300</altitud>
        </coordenadas>
        <distancia_salida unidad="km">50.5</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Rotonda derecha dirección Vila</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5790</longitud_geo>
            <latitud_geo unidad="grados">42.5342</latitud_geo>
            <altitud unidad="m">1310</altitud>
        </coordenadas>
