=== UO306603/SEW/xml/etapa.dtd
<!ELEMENT etapa (nombre, numero, longitud_etapa, fecha, tiempo_ganador, velocidad_media, desnivel, inicio, meta, tipo, referencias, galeria_fotografias, galeria_videos, galeria_audios, hitos, puntos_anonimos, clasificacion_etapa, clasificacion_general, clasificacion_equipos)>

<!--ETAPA-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT longitud_etapa (#PCDATA)>
<!ATTLIST longitud_etapa unidad CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempo_ganador (#PCDATA)>
<!ELEMENT velocidad_media (#PCDATA)>
<!ATTLIST velocidad_media unidad CDATA #REQUIRED>
<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidad CDATA #REQUIRED>
<!ELEMENT tipo (#PCDATA)>

<!--INICIO Y META-->
<!ELEMENT inicio (ciudad, coordenadas)>
<!ELEMENT meta (ciudad, coordenadas)>
<!ELEMENT ciudad (#PCDATA)>

<!--COORDENADAS-->
<!ELEMENT coordenadas (longitud_geo, latitud_geo, altitud)>
<!ELEMENT longitud_geo (#PCDATA)>
<!ATTLIST longitud_geo unidad CDATA #REQUIRED>
<!ELEMENT latitud_geo (#PCDATA)>
<!ATTLIST latitud_geo unidad CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED>

<!--REFERENCIAS-->
<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>

<!--GALERIA FOTOS-->
<!ELEMENT galeria_fotografias (fotografia, fotografia?, fotografia?, fotografia?, fotografia?)>
<!ELEMENT fotografia (#PCDATA)>
<!--GALERIA VIDEOS-->
<!ELEMENT galeria_videos (video, video?, video?)>
<!ELEMENT video (#PCDATA)>
<!--GALERIA AUDIOS-->
<!ELEMENT galeria_audios (audio, audio?, audio?)>
<!ELEMENT audio (#PCDATA)>

<!--HITOS-->
<!ELEMENT hitos (puerto_montana | sprint)*>
<!ELEMENT puerto_montana (nombre_hito, categoria, coordenadas, distancia_salida)>
<!ELEMENT sprint (nombre_hito,tipo_sprint, coordenadas, distancia_salida)>
<!ELEMENT nombre_hito (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT tipo_sprint (#PCDATA)>

<!ELEMENT distancia_salida (#PCDATA)>
<!ATTLIST distancia_salida unidad CDATA #REQUIRED>

<!--PUNTOS ANÓNIMOS-->
<!ELEMENT puntos_anonimos (punto_anonimo*)>
<!ELEMENT punto_anonimo (nombre_punto?, coordenadas, distancia_salida)>
<!ELEMENT nombre_punto (#PCDATA)>

<!--CLASIFICACIONES-->
<!ELEMENT clasificacion_etapa (primero, segundo, tercero)>
<!ELEMENT clasificacion_general (primero, segundo, tercero)>
<!ELEMENT clasificacion_equipos (equipo_primero, equipo_segundo, equipo_tercero)>

<!ELEMENT primero (nombre_participante, tiempo)>
<!ELEMENT segundo (nombre_participante, diferencia)>
<!ELEMENT tercero (nombre_participante, diferencia)>

<!ELEMENT equipo_primero (nombre_equipo, tiempo)>
<!ELEMENT equipo_segundo (nombre_equipo, diferencia)>
<!ELEMENT equipo_tercero (nombre_equipo, diferencia)>

<!--ELEMENTOS CLASIFICACIONES-->
<!ELEMENT nombre_participante (#PCDATA)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT diferencia (#PCDATA)>

=== UO306603/SEW/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
<etapa>
    <nombre>Andorra la Vella a Andorra la Vella</nombre>
    <numero>4</numero>
    <longitud_etapa unidad="km">104.8</longitud_etapa>
    <fecha>25-08-2026</fecha>
    <tiempo_ganador>2:40:35</tiempo_ganador>
    <velocidad_media unidad="km/h">39,157</velocidad_media>
    <desnivel unidad="m">2953</desnivel>
    
    <inicio>
        <ciudad>Andorra la Vella</ciudad>
        <coordenadas>
            <longitud_geo unidad="grados decimales">1.5211</longitud_geo>
            <latitud_geo unidad="grados decimales">42.5078</latitud_geo>
            <altitud unidad="m">1023 </altitud>
        </coordenadas>
    </inicio>
    
    <meta>
        <ciudad>Andorra la Vella</ciudad>
         <coordenadas>
            <longitud_geo unidad="grados decimales">1.5211</longitud_geo>
            <latitud_geo unidad="grados decimales">42.5078</latitud_geo>
            <altitud unidad="m">1023 </altitud>
        </coordenadas>
    </meta>
    
    <tipo>montaña</tipo>
    
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-4</referencia>
        <referencia>https://www.lavuelta.es/es/clasificaciones/etapa-4</referencia>
        <referencia>https://www.lavuelta.es/es/video/3610/minuto-maillot-rojo-carrefour-etapa-4-la-vuelta-26</referencia>
    </referencias>
    
    <galeria_fotografias>
        <fotografia>foto1</fotografia>
        <fotografia>foto2</fotografia>
        <fotografia>foto3</fotografia>
    </galeria_fotografias>
    
    <galeria_videos>
        <video>video1</video>
        <video>video2</video>
    </galeria_videos>
    
    <galeria_audios>
        <audio>audio1</audio>
        <audio>audio2</audio>
    </galeria_audios>
    
    <hitos>
        <!-- Puerto 1: Port d'Envalira -->
    <puerto_montana>
        <nombre_hito>Port d'Envalira</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.71989</longitud_geo>
            <latitud_geo unidad="grados">42.54037</latitud_geo>
            <altitud unidad="m">2409 </altitud>
        </coordenadas>
        <distancia_salida unidad="km">25.1</distancia_salida>
    </puerto_montana>

    <!-- Puerto 2: Collada de Beixalis -->
    <puerto_montana>
        <nombre_hito>Collada de Beixalis</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.54771</longitud_geo>
            <latitud_geo unidad="grados">42.52908</latitud_geo>
            <altitud unidad="m">1795</altitud>
        </coordenadas>
        <distancia_salida unidad="km">59.3</distancia_salida>
    </puerto_montana>

    <!-- Sprint 1: Ordino -->
    <sprint>
        <nombre_hito>Ordino</nombre_hito>
        <tipo_sprint>Intermedio</tipo_sprint>
        <coordenadas>
            <longitud_geo unidad="grados">1.53319</longitud_geo>
            <latitud_geo unidad="grados">42.55623</latitud_geo>
            <altitud unidad="m">1298</altitud>
        </coordenadas>
        <distancia_salida unidad="km">68.4</distancia_salida>
    </sprint>

    <!-- Puerto 3: Col de Ordino -->
    <puerto_montana>
        <nombre_hito>Col de Ordino</nombre_hito>
        <categoria>1ª</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.5722</longitud_geo>
            <latitud_geo unidad="grados">42.5561</latitud_geo>
            <altitud unidad="m">1980</altitud>
        </coordenadas>
        <distancia_salida unidad="km">78.7</distancia_salida>
    </puerto_montana>

    <!-- Puerto 4: Alto de La Comella -->
    <puerto_montana>
        <nombre_hito>Alto de La Comella</nombre_hito>
        <categoria>3ª,Bonificado</categoria>
        <coordenadas>
            <longitud_geo unidad="grados">1.531415</longitud_geo>
            <latitud_geo unidad="grados">42.500534</latitud_geo>
            <altitud unidad="m">1347</altitud>
        </coordenadas>
        <distancia_salida unidad="km">100.0</distancia_salida>
    </puerto_montana>
    </hitos>
    
    <puntos_anonimos>
    <punto_anonimo>
        <nombre_punto>Encamp</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5822</longitud_geo>
            <latitud_geo unidad="grados">42.5361</latitud_geo>
            <altitud unidad="m">1300</altitud>
        </coordenadas>
        <distancia_salida unidad="km">1.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Comienza puerto</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5830</longitud_geo>
            <latitud_geo unidad="grados">42.5370</latitud_geo>
            <altitud unidad="m">1310</altitud>
        </coordenadas>
        <distancia_salida unidad="km">1.8</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Canillo</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5977</longitud_geo>
            <latitud_geo unidad="grados">42.5667</latitud_geo>
            <altitud unidad="m">1530</altitud>
        </coordenadas>
        <distancia_salida unidad="km">8.1</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>El Tarter</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6531</longitud_geo>
            <latitud_geo unidad="grados">42.5794</latitud_geo>
            <altitud unidad="m">1710</altitud>
        </coordenadas>
        <distancia_salida unidad="km">13.2</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Soldeu</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6678</longitud_geo>
            <latitud_geo unidad="grados">42.5767</latitud_geo>
            <altitud unidad="m">1825</altitud>
        </coordenadas>
        <distancia_salida unidad="km">15.8</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Pas de la Casa</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7336</longitud_geo>
            <latitud_geo unidad="grados">42.5428</latitud_geo>
            <altitud unidad="m">2080</altitud>
        </coordenadas>
        <distancia_salida unidad="km">29.9</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Francia</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7380</longitud_geo>
            <latitud_geo unidad="grados">42.5440</latitud_geo>
            <altitud unidad="m">2085</altitud>
        </coordenadas>
        <distancia_salida unidad="km">30.3</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Andorra</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7350</longitud_geo>
            <latitud_geo unidad="grados">42.5430</latitud_geo>
            <altitud unidad="m">2070</altitud>
        </coordenadas>
        <distancia_salida unidad="km">31.1</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Tunel 2.870 metros iluminado</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.7198</longitud_geo>
            <latitud_geo unidad="grados">42.5453</latitud_geo>
            <altitud unidad="m">2000</altitud>
        </coordenadas>
        <distancia_salida unidad="km">31.4</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>pasos estrechos por casetas de peaje</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6912</longitud_geo>
            <latitud_geo unidad="grados">42.5580</latitud_geo>
            <altitud unidad="m">1950</altitud>
        </coordenadas>
        <distancia_salida unidad="km">34.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Soldeu</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6678</longitud_geo>
            <latitud_geo unidad="grados">42.5767</latitud_geo>
            <altitud unidad="m">1825</altitud>
        </coordenadas>
        <distancia_salida unidad="km">38.7</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>El Tarter</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.6531</longitud_geo>
            <latitud_geo unidad="grados">42.5794</latitud_geo>
            <altitud unidad="m">1710</altitud>
        </coordenadas>
        <distancia_salida unidad="km">41.0</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Canillo</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5977</longitud_geo>
            <latitud_geo unidad="grados">42.5667</latitud_geo>
            <altitud unidad="m">1530</altitud>
        </coordenadas>
        <distancia_salida unidad="km">46.0</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Encamp</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5822</longitud_geo>
            <latitud_geo unidad="grados">42.5361</latitud_geo>
            <altitud unidad="m">1300</altitud>
        </coordenadas>
        <distancia_salida unidad="km">50.5</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
        <nombre_punto>Rotonda derecha dirección Vila</nombre_punto>
        <coordenadas>
            <longitud_geo unidad="grados">1.5790</longitud_geo>
            <latitud_geo unidad="grados">42.5342</latitud_geo>
            <altitud unidad="m">1310</altitud>
        </coordenadas>
        <distancia_salida unidad="km">52.1</distancia_salida>
    </punto_anonimo>

    <punto_anonimo>
